name: CD

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build (Release)
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Clear
      run: dotnet clean && dotnet nuget locals all --clear

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build PTI-Ear-Trainer/PTI-Ear-Trainer.csproj -c Release -o release

    - name: Execute unit tests
      run: dotnet test -c Release

    - name: Zip artifact
      shell: powershell
      run: Compress-Archive -Path release\* -DestinationPath PTI-Ear-Trainer.zip

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        default_bump: minor
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        generate_release_notes: true
        files: "PTI-Ear-Trainer.zip"
